"""Add Reasoning Engine MVP tables

Revision ID: 97bae0b6dd5b
Revises: e28249874ca7
Create Date: 2026-06-27 10:21:40.574650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97bae0b6dd5b'
down_revision: Union[str, Sequence[str], None] = 'e28249874ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_instances',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('entities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('source_evidence_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.evidence_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_impacts',
    sa.Column('impact_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('impact_type', sa.String(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['kg_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event_instances.event_id'], ),
    sa.PrimaryKeyConstraint('impact_id')
    )
    op.create_table('reasoning_paths',
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('start_entity_id', sa.String(), nullable=True),
    sa.Column('end_entity_id', sa.String(), nullable=True),
    sa.Column('nodes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('path_score', sa.Float(), nullable=False),
    sa.Column('path_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_instances.event_id'], ),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('stock_event_scores',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('volume_score', sa.Float(), nullable=True),
    sa.Column('event_intensity', sa.Float(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_instances.event_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'stock_code')
    )
    op.create_table('stock_exposures',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason_path_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['kg_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event_instances.event_id'], ),
    sa.ForeignKeyConstraint(['reason_path_id'], ['reasoning_paths.path_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'stock_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_exposures')
    op.drop_table('stock_event_scores')
    op.drop_table('reasoning_paths')
    op.drop_table('event_impacts')
    op.drop_table('event_instances')
    # ### end Alembic commands ###
