"""Init V1 and V2 schema

Revision ID: e28249874ca7
Revises: 
Create Date: 2026-06-27 01:31:03.057549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e28249874ca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('merged_into_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('extractor_type', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('candidate_relations',
    sa.Column('relation_id', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('extractor_type', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('commodity_impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('impact_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commodity_sector_mappings',
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('commodity', 'sector')
    )
    op.create_table('company_commodity_profiles',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('benefit_when_price_up', sa.Integer(), nullable=False),
    sa.Column('benefit_when_price_down', sa.Integer(), nullable=False),
    sa.Column('exposure_strength', sa.Float(), nullable=False),
    sa.Column('pricing_power', sa.Float(), nullable=False),
    sa.Column('inventory_sensitivity', sa.Float(), nullable=False),
    sa.Column('pass_through_ability', sa.Float(), nullable=False),
    sa.Column('earnings_elasticity', sa.Float(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'commodity')
    )
    op.create_table('daily_prices',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'trade_date')
    )
    op.create_table('event_earnings_impacts',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('revenue_impact_score', sa.Float(), nullable=False),
    sa.Column('margin_impact_score', sa.Float(), nullable=False),
    sa.Column('profit_impact_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'symbol', 'commodity')
    )
    op.create_table('event_stock_reaction_scores_v2',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('shock_score', sa.Float(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('earnings_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('reaction_score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('transmission_chain', sa.String(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'symbol', 'commodity')
    )
    op.create_table('event_stock_scores',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_score', sa.Float(), nullable=False),
    sa.Column('event_impact', sa.Float(), nullable=False),
    sa.Column('sector_exposure', sa.Float(), nullable=False),
    sa.Column('trend_strength', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('causal_chain', sa.String(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'symbol')
    )
    op.create_table('event_validation_results',
    sa.Column('validation_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('stock_code', sa.String(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=True),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('t0_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('absolute_return', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('industry_return', sa.Float(), nullable=True),
    sa.Column('excess_return_index', sa.Float(), nullable=True),
    sa.Column('excess_return_industry', sa.Float(), nullable=True),
    sa.Column('max_gain', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('news_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('extraction_source', sa.String(), nullable=False),
    sa.Column('extraction_raw_output', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('related_company', sa.String(), nullable=True),
    sa.Column('related_stock_code', sa.String(), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('jobs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('kg_change_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('relation_id', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kg_entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('merged_into_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('score_source', sa.String(), nullable=False),
    sa.Column('model_raw_output', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_stock_links',
    sa.Column('news_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('news_id', 'symbol')
    )
    op.create_table('sector_stock_exposures',
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('sector', 'symbol')
    )
    op.create_table('signals',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal_date', sa.String(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('volume_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('burst', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metrics', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'signal_date')
    )
    op.create_table('stock_aliases',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('alias', 'symbol')
    )
    op.create_table('stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('validation_summary',
    sa.Column('summary_id', sa.String(), nullable=False),
    sa.Column('summary_type', sa.String(), nullable=False),
    sa.Column('summary_key', sa.String(), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('avg_excess_return', sa.Float(), nullable=False),
    sa.Column('weight_adjustment', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('kg_relations',
    sa.Column('relation_id', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['kg_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['kg_entities.entity_id'], ),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('relation_evidence',
    sa.Column('relation_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('support_type', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.String(), nullable=False),
    sa.Column('confidence_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['kg_relations.relation_id'], ),
    sa.PrimaryKeyConstraint('relation_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_evidence')
    op.drop_table('kg_relations')
    op.drop_table('validation_summary')
    op.drop_table('stocks')
    op.drop_table('stock_aliases')
    op.drop_table('signals')
    op.drop_table('sector_stock_exposures')
    op.drop_table('news_stock_links')
    op.drop_table('news_items')
    op.drop_table('kg_entities')
    op.drop_table('kg_change_logs')
    op.drop_table('jobs')
    op.drop_table('evidence')
    op.drop_table('events')
    op.drop_table('event_validation_results')
    op.drop_table('event_stock_scores')
    op.drop_table('event_stock_reaction_scores_v2')
    op.drop_table('event_earnings_impacts')
    op.drop_table('daily_prices')
    op.drop_table('company_commodity_profiles')
    op.drop_table('commodity_sector_mappings')
    op.drop_table('commodity_impacts')
    op.drop_table('candidate_relations')
    op.drop_table('candidate_entities')
    # ### end Alembic commands ###
